import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import ProductCard from '../components/ProductCard'
import ReactCarousal from '../components/ReactCarousal'
import ProductSlider from "../components/ProductSlider"
import Banner from '../components/Banner'


export default function Home({data}) {
  return (
    <div className="">
      <Head>
        <title>Ecommerce shop </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <div className=''>
    <ReactCarousal/>
    <ProductSlider data={data}/>
  <Banner/>
    <ProductCard data={data.slice(0,8)}/>
     </div>
    </div>
  )
}


export async function getServerSideProps(context) {
  // const { data } =await axios.get("https://fakestoreapi.com/products");
  const res =await fetch("http://localhost:3000/api/getproducts");
  const data=await res.json()

  
  return {
    props: {
      data: data,
    },
  };
}
